/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RulesCreateRouteImport } from './routes/rules/create'
import { Route as RulesEditRuleIdRouteImport } from './routes/rules/edit/$ruleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesCreateRoute = RulesCreateRouteImport.update({
  id: '/rules/create',
  path: '/rules/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesEditRuleIdRoute = RulesEditRuleIdRouteImport.update({
  id: '/rules/edit/$ruleId',
  path: '/rules/edit/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules/create': typeof RulesCreateRoute
  '/settings/': typeof SettingsIndexRoute
  '/rules/edit/$ruleId': typeof RulesEditRuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules/create': typeof RulesCreateRoute
  '/settings': typeof SettingsIndexRoute
  '/rules/edit/$ruleId': typeof RulesEditRuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules/create': typeof RulesCreateRoute
  '/settings/': typeof SettingsIndexRoute
  '/rules/edit/$ruleId': typeof RulesEditRuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rules/create' | '/settings/' | '/rules/edit/$ruleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rules/create' | '/settings' | '/rules/edit/$ruleId'
  id: '__root__' | '/' | '/rules/create' | '/settings/' | '/rules/edit/$ruleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesCreateRoute: typeof RulesCreateRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  RulesEditRuleIdRoute: typeof RulesEditRuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/create': {
      id: '/rules/create'
      path: '/rules/create'
      fullPath: '/rules/create'
      preLoaderRoute: typeof RulesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/edit/$ruleId': {
      id: '/rules/edit/$ruleId'
      path: '/rules/edit/$ruleId'
      fullPath: '/rules/edit/$ruleId'
      preLoaderRoute: typeof RulesEditRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesCreateRoute: RulesCreateRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  RulesEditRuleIdRoute: RulesEditRuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
